// <auto-generated />
using System;
using E_wallet.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace E_wallet.Infrastrucure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251010201129_MakeProfileIdNullable")]
    partial class MakeProfileIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("E_wallet.Domain.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CraetedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("FullName ");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive ");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Phone ");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Admin_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Phone", "Email" }, "Uniqe-value")
                        .IsUnique();

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("CreatedAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("NewItemSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NewItemSnapshotJSON");

                    b.Property<string>("OldItemSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OldItemSnapshotJSON");

                    b.Property<TimeOnly?>("UpdatedAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("AuditLog_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Beneficiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("BeneficiaryWalletId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("CreatedAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Purpos")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<TimeOnly?>("UpdatedAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName(" UpdatedBy");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Beneficiary _pkey");

                    b.HasIndex("BeneficiaryWalletId");

                    b.HasIndex("WalletId");

                    b.ToTable("Beneficiary ");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Limit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("CreatedAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<TimeOnly?>("UpdatedAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("Value ");

                    b.HasKey("Id")
                        .HasName("Limit_pkey");

                    b.ToTable("Limit");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Event ");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("time with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Notification_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Profile_pkey");

                    b.HasIndex(new[] { "Phone" }, "Unique-Values")
                        .IsUnique();

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Role _pkey");

                    b.ToTable("Role ");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("CraetedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeOnly?>("ExpiresAt")
                        .HasColumnType("time without time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("RefreshExpiresAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Session_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int>("BeneficiaryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("TransferId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("character varying");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Transaction_pkey");

                    b.HasIndex("TransferId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("Fee")
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ReciverWalletId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderWalletId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Transfer_pkey");

                    b.HasIndex("ReciverWalletId");

                    b.HasIndex("SenderWalletId");

                    b.ToTable("Transfer");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Createdby")
                        .HasColumnType("character varying");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Updatedby")
                        .HasColumnType("character varying");

                    b.HasKey("Id")
                        .HasName("User_pkey");

                    b.HasIndex("ProfileId");

                    b.HasIndex(new[] { "Password", "Email" }, "Uniqe-Values")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.UserBankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<int>("BankId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("CreatedAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("character varying");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("UpdatedAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("UserBankAccount_pkey");

                    b.HasIndex("BankId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBankAccount");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.VirtualBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("UpdatedAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("VirtualBank_pkey");

                    b.HasIndex("WalletId");

                    b.ToTable("VirtualBank");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<double?>("Ballance")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Currency")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Wallet_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Admin", b =>
                {
                    b.HasOne("E_wallet.Domain.Entities.Role", "Role")
                        .WithMany("Admins")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("Fk-RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("E_wallet.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Fk-UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Beneficiary", b =>
                {
                    b.HasOne("E_wallet.Domain.Entities.Wallet", "BeneficiaryWallet")
                        .WithMany("BeneficiaryBeneficiaryWallets")
                        .HasForeignKey("BeneficiaryWalletId")
                        .IsRequired()
                        .HasConstraintName("Fk-BeneficiaryWalletId");

                    b.HasOne("E_wallet.Domain.Entities.Wallet", "Wallet")
                        .WithMany("BeneficiaryWallets")
                        .HasForeignKey("WalletId")
                        .IsRequired()
                        .HasConstraintName("Fk-WalletId");

                    b.Navigation("BeneficiaryWallet");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Notification", b =>
                {
                    b.HasOne("E_wallet.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Fk-UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Session", b =>
                {
                    b.HasOne("E_wallet.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Fk-UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("E_wallet.Domain.Entities.Transfer", "Transfer")
                        .WithMany("Transactions")
                        .HasForeignKey("TransferId")
                        .HasConstraintName("Fk-TransferId");

                    b.HasOne("E_wallet.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .IsRequired()
                        .HasConstraintName("Fk-WalletId");

                    b.Navigation("Transfer");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Transfer", b =>
                {
                    b.HasOne("E_wallet.Domain.Entities.Wallet", "ReciverWallet")
                        .WithMany("TransferReciverWallets")
                        .HasForeignKey("ReciverWalletId")
                        .IsRequired()
                        .HasConstraintName("Fk-ReciverWalletId");

                    b.HasOne("E_wallet.Domain.Entities.Wallet", "SenderWallet")
                        .WithMany("TransferSenderWallets")
                        .HasForeignKey("SenderWalletId")
                        .IsRequired()
                        .HasConstraintName("Fk-SenderWalletId");

                    b.Navigation("ReciverWallet");

                    b.Navigation("SenderWallet");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.User", b =>
                {
                    b.HasOne("E_wallet.Domain.Entities.Profile", "Profile")
                        .WithMany("Users")
                        .HasForeignKey("ProfileId")
                        .HasConstraintName("Fk-ProfileId");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.UserBankAccount", b =>
                {
                    b.HasOne("E_wallet.Domain.Entities.VirtualBank", "Bank")
                        .WithMany("UserBankAccounts")
                        .HasForeignKey("BankId")
                        .IsRequired()
                        .HasConstraintName("Fk-BankId");

                    b.HasOne("E_wallet.Domain.Entities.User", "User")
                        .WithMany("UserBankAccounts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Fk-UserId");

                    b.Navigation("Bank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.VirtualBank", b =>
                {
                    b.HasOne("E_wallet.Domain.Entities.Wallet", "Wallet")
                        .WithMany("VirtualBanks")
                        .HasForeignKey("WalletId")
                        .IsRequired()
                        .HasConstraintName("Fk-WalletId");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("E_wallet.Domain.Entities.User", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Fk-UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Profile", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Role", b =>
                {
                    b.Navigation("Admins");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Transfer", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Notifications");

                    b.Navigation("Sessions");

                    b.Navigation("UserBankAccounts");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.VirtualBank", b =>
                {
                    b.Navigation("UserBankAccounts");
                });

            modelBuilder.Entity("E_wallet.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("BeneficiaryBeneficiaryWallets");

                    b.Navigation("BeneficiaryWallets");

                    b.Navigation("Transactions");

                    b.Navigation("TransferReciverWallets");

                    b.Navigation("TransferSenderWallets");

                    b.Navigation("VirtualBanks");
                });
#pragma warning restore 612, 618
        }
    }
}
